### ISSUE TITLE
Error with plugin ? or connection ?

### ISSUE THREAD

**Issue by fastenspy** [codyc1515/homebridge-sma-inverter#12]
Hello i have this problème (but sma plugin is loaded)
<img width="930" alt="Capture d’écran 2020-03-26 à 08 12 54" src="https://user-images.githubusercontent.com/14542142/77620519-d6c14c80-6f3a-11ea-8853-3bd899128914.png">

**Comment by codyc1515** [comment]
Hopefully the IP address issue should be fixed now in https://github.com/codyc1515/homebridge-sma-inverter/commit/94d1c2cd2b33ccf5b3542ac57defab978135c1c9. Can you let me know?

**Comment by fastenspy** [comment]
Hello, Just reinstall this plugin and now I have this:
Tested with IP address and SMAxxx.local it's the same ! And I'm sure for ip and address...




`[5/19/2020, 17:05:11] [SMA] Failed to connect to the SMA Inverter, attempting to reconnect... TypeError: Cannot read property 'buffer' of undefined
    at SMAInverter.<anonymous> (/usr/lib/node_modules/homebridge-sma-inverter/index.js:150:17)
    at ModbusRTU.writeFC4 (/usr/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:544:19)
    at ModbusRTU.writeFC3 (/usr/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:530:10)
    at ModbusRTU.converted [as readHoldingRegisters] (/usr/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/apis/promise.js:36:27)
    at SMAInverter._refresh (/usr/lib/node_modules/homebridge-sma-inverter/index.js:149:11)
    at SMAInverter.<anonymous> (/usr/lib/node_modules/homebridge-sma-inverter/index.js:140:9)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:599) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 192.168.1.204:502
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
(node:599) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)`

**Comment by fastenspy** [comment]
Just active debug:

<img width="1626" alt="Capture d’écran 2020-05-19 à 18 11 45" src="https://user-images.githubusercontent.com/14542142/82351019-524fef00-99fc-11ea-8a5a-e58efd55b8f0.png">

**Comment by codyc1515** [comment]
Looks like it doesn’t support ModBus.
