### ISSUE TITLE
Which IP is required?

### ISSUE THREAD

**Issue by urbanfrank** [codyc1515/homebridge-sma-inverter#18]
The Ip of the Tri Power or the Ip of the Home Manager? Both of them do not reach the port. I found the port in the configuration of the Tripower. But it is deactivated and I do not have the rights I will ask the service provider.

I have a SUNNY TRIPOWER 5.0

thx 

Frank

Error:
[29/11/2020, 15:02:29] [SMA Inverter] Refresh failed Attempting reconnect... TypeError: Cannot read property 'buffer' of undefined
    at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:168:13)
    at ModbusRTU.writeFC4 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:544:19)
    at ModbusRTU.writeFC3 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:530:10)
    at ModbusRTU.converted [as readHoldingRegisters] (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/apis/promise.js:36:27)
    at SMAInverter._refresh (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:166:11)
    at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:99:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:7948) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED *.*.*.*:502
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(node:7948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 37)

![Bildschirmfoto 2020-11-29 um 15 01 18](https://user-images.githubusercontent.com/75209985/100544112-cbee5280-3253-11eb-95ad-fef1a87b20b8.png)

**Comment by codyc1515** [comment]
You need to turn on ModBus on the TriPower. Note I haven't got a TriPower to test with. I use Sunny Boy. So it may not work.
