### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by dannywanwan** [codyc1515/homebridge-sma-inverter#23]
[1/4/2021, 7:34:54 PM] [SMA Inverter] Attempting connection 10.1.1.2
[1/4/2021, 7:34:54 PM] [SMA Inverter] Connection successful
(node:15109) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 10.1.1.2:502
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:15109) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 991)
[1/4/2021, 7:34:55 PM] [SMA Inverter] Refresh failed Attempting reconnect... TypeError: Cannot read property 'buffer' of undefined
    at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:168:13)
    at ModbusRTU.writeFC4 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:544:19)
    at ModbusRTU.writeFC3 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:530:10)
    at ModbusRTU.converted [as readHoldingRegisters] (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/apis/promise.js:36:27)
    at SMAInverter._refresh (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:166:11)
    at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:99:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by mitch7391** [comment]
This sounds like the problem I had in #21, have a look over that :)

**Comment by dannywanwan** [comment]
Amazing. Thanks @mitch7391! Luckily my installer gave me the password

**Comment by mitch7391** [comment]
I was lucky that my installer gave me the password too :) glad to hear it help! I think we need a good README so people don’t keep creating this issue @codyc1515.
