### ISSUE TITLE
Cannot connect to Sunny Boy 4.0

### ISSUE THREAD

**Issue by vrxj81** [codyc1515/homebridge-sma-inverter#29]
I probably did something wrong, but I'm getting this error:
`[11/04/2021, 16:00:00] [SB4.0-1AV-41 277] Refresh failed Attempting reconnect... TypeError: Cannot read property 'buffer' of undefined
    at SMAInverter.<anonymous> (/opt/node/node-v14.16.1-linux-armv6l/lib/node_modules/homebridge-sma-inverter/index.js:168:13)
    at ModbusRTU.writeFC4 (/opt/node/node-v14.16.1-linux-armv6l/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:544:19)
    at ModbusRTU.writeFC3 (/opt/node/node-v14.16.1-linux-armv6l/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:530:10)
    at ModbusRTU.converted [as readHoldingRegisters] (/opt/node/node-v14.16.1-linux-armv6l/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/apis/promise.js:36:27)
    at SMAInverter._refresh (/opt/node/node-v14.16.1-linux-armv6l/lib/node_modules/homebridge-sma-inverter/index.js:166:11)
    at SMAInverter.<anonymous> (/opt/node/node-v14.16.1-linux-armv6l/lib/node_modules/homebridge-sma-inverter/index.js:99:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[11/04/2021, 16:00:00] [SB4.0-1AV-41 277] Attempting connection 192.168.0.142
[11/04/2021, 16:00:00] [SB4.0-1AV-41 277] Connection successful
(node:11090) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 192.168.0.142:502
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(node:11090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 109)`

**Comment by vrxj81** [comment]
Never mind, I figured out how to login and set up the TCP servers on the ModBus
