### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by helander** [codyc1515/homebridge-sma-inverter#32]
I get the following error when trying to use this plugin:

`[08/06/2021, 09:20:45] [SMA Inverter] Refresh failed Attempting reconnect... TypeError: Cannot read property 'buffer' of undefined
    at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:168:13)
    at ModbusRTU.writeFC4 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:544:19)
    at ModbusRTU.writeFC3 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:530:10)
    at ModbusRTU.converted [as readHoldingRegisters] (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/apis/promise.js:36:27)
    at SMAInverter._refresh (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:166:11)
    at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:99:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[08/06/2021, 09:20:45] [SMA Inverter] Attempting connection sma3010290187.local
[08/06/2021, 09:20:45] [SMA Inverter] Connection successful
(node:6266) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 192.168.68.120:502
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(node:6266) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 78)
`

**Comment by helander** [comment]
I found the problem. No MODBUS server was running on my inverter. Activated the server via manual configuration of the inverter.
