### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by cohen-sydney** [codyc1515/homebridge-sma-inverter#42]
not showing as tiles in room, not showing as individual tiles. shows as 839 lux at top 

**Paste of Logs:**
14/05/2022, 09:41:09] [SMA Inverter] Refresh failed Attempting reconnect... TypeError: Cannot read properties of undefined (reading 'buffer')
    at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:168:13)
    at ModbusRTU.writeFC4 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:544:19)
    at ModbusRTU.writeFC3 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:530:10)
    at ModbusRTU.converted [as readHoldingRegisters] (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/apis/promise.js:36:27)
    at SMAInverter._refresh (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:166:11)
    at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:99:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)```

**Config:**

{
    "name": "SMA Inverter",
    "hostname": "192.168.123.20",
    "refreshInterval": 1,
    "accessory": "SMAInverter"
}

**Screenshots:**

<img width="926" alt="Screen Shot 2022-05-14 at 9 54 50 am" src="https://user-images.githubusercontent.com/17312304/168402445-0e00223c-0b94-405c-baf7-31dd7a1f4bbd.png">

**Inverter:**

SUNNY TRIPOWER 8.0

STP8.0-3AV-40 739

* **Model:** 

**Homebridge Environment:**

* **Node.js Version**: 16.14.0 
* **NPM Version**: not sure
* **Homebridge Version**:  1.4.1 
* **homebridge-sma-inverter Version**: homebridge-sma-inverter v3.3.0
* **Operating System**: Raspbian

**Comment by cohen-sydney** [comment]
they show ok on the HomeBridge Accessories page.
<img width="520" alt="Screen Shot 2022-05-14 at 12 50 23 pm" src="https://user-images.githubusercontent.com/17312304/168408108-ef117789-71be-443f-86d1-9aacb28a87ef.png">

**Comment by mitch7391** [comment]
@cohen-sydney this is just how HomeKit displays them and not an issue with this plug-in. It is the same with temperature sensors, they will display is the status bar at the top but not as tiles in the room; will also display as tiles in Homebridge.

**Comment by pmahli** [comment]
Fellas
I have tried everything to get this up and running and connecting my Sunny Tripower 6.0 to Homebridge.  

[03/07/2022, 15:20:36] [SMA Inverter] Attempting connection 192.168.178.61
[03/07/2022, 15:20:36] [SMA Inverter] Connection successful
[03/07/2022, 15:20:36] Error: connect **ECONNREFUSED** 192.168.178.61:502
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
[03/07/2022, 15:20:37] [SMA Inverter] Refresh failed Attempting reconnect... TypeError: Cannot read properties of undefined (reading 'buffer')
    at SMAInverter.<anonymous> (/var/lib/homebridge/node_modules/homebridge-sma-inverter/index.js:168:13)
    at ModbusRTU.writeFC4 (/var/lib/homebridge/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:544:19)
    at ModbusRTU.writeFC3 (/var/lib/homebridge/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:530:10)
    at ModbusRTU.converted [as readHoldingRegisters] (/var/lib/homebridge/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/apis/promise.js:36:27)
    at SMAInverter._refresh (/var/lib/homebridge/node_modules/homebridge-sma-inverter/index.js:166:11)
    at SMAInverter.<anonymous> (/var/lib/homebridge/node_modules/homebridge-sma-inverter/index.js:99:8)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

I am running:
OS	Raspbian GNU/Linux Bullseye (11)
Node.js Version	[v16.15.1](https://homebridge.io/w/JTKEF)

Any idea what I am overseeing?

**Comment by mitch7391** [comment]
@pmahli I might be wrong but from memory the Tripower is not supported as it does not use modbus? I just searched an old issue where it is mentioned [here.](https://github.com/codyc1515/homebridge-sma-inverter/issues/28#issuecomment-812307890)

**Comment by pmahli** [comment]
@mitch7391, thx for your reply. Wasn’t aware of that.
