### ISSUE TITLE
error in line 137 

### ISSUE THREAD

**Issue by rangerek** [codyc1515/homebridge-sma-inverter#8]
after using the temporary fix from #6 and being able to connect to inverter i get following error:
```
Nov 08 11:34:42 homebridge homebridge[2052]: [11/8/2019, 11:34:42 AM] [Solar Inverter] Failed to connect to the SMA Inverter TypeError: Cannot read property 'buffer' of undefined
Nov 08 11:34:42 homebridge homebridge[2052]:     at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:137:25)
Nov 08 11:34:42 homebridge homebridge[2052]:     at ModbusRTU.writeFC4 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:501:19)
Nov 08 11:34:42 homebridge homebridge[2052]:     at ModbusRTU.writeFC3 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:487:10)
Nov 08 11:34:42 homebridge homebridge[2052]:     at ModbusRTU.converted [as readHoldingRegisters] (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/apis/promise.js:36:27)
Nov 08 11:34:42 homebridge homebridge[2052]:     at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:136:19)
Nov 08 11:34:42 homebridge homebridge[2052]:     at ontimeout (timers.js:436:11)
Nov 08 11:34:42 homebridge homebridge[2052]:     at tryOnTimeout (timers.js:300:5)
Nov 08 11:34:42 homebridge homebridge[2052]:     at listOnTimeout (timers.js:263:5)
Nov 08 11:34:42 homebridge homebridge[2052]:     at Timer.processTimers (timers.js:223:10)
```
however the tile is visible in HK and what more, this error does not kill homebridge itself

**Comment by rangerek** [comment]
found a solution - but it should not work that way :( 
root@homebridge:~# npm outdated
Package     Current  Wanted  Latest  Location
serialport    7.1.5   7.1.5   8.0.5  global

after manual update it works
