### ISSUE TITLE
Homemanager?

### ISSUE THREAD

**Issue by solbadguy2010** [codyc1515/homebridge-sma-inverter#9]
Hi!
Am i able to use this Plugin with my SMA Homemanager?

**Comment by codyc1515** [comment]
Does it support ModBus?

**Comment by solbadguy2010** [comment]
I really do not know. Is there some way i. An test this?

**Comment by codyc1515** [comment]
You will need to install the plugin and try it.

**Comment by solbadguy2010** [comment]
Tried it. This is the result. 
![C8BDD863-360A-4992-B93A-EEC3264AECA3](https://user-images.githubusercontent.com/30244171/82311190-a8ee0680-99c5-11ea-9522-d696c3651d36.png)

**Comment by codyc1515** [comment]
Looks like ModBus is not supported.

**Comment by solbadguy2010** [comment]
I think i needed to activate it. But the manual metions modbus and port 502 on page 93. Sorry, its german. Is this the correct port?

http://www.moeller.eu/pages/config_download.php?Datei=pv_dl_sma_sunnyhomemanager_ba_de.pdf

**Comment by codyc1515** [comment]
Yes. Bear in mind the ModBus "registers" may well be different between the Home Manager and the Sunny Boy Inverters for which this plug-in is designed.

**Comment by solbadguy2010** [comment]
Ok. I activated the setting, rebootet the Home Manager and now get this error with IP and and debug logging active:

`[5/20/2020, 08:13:05] TypeError: Cannot read property 'buffer' of undefined
    at SMAInverter.<anonymous> (/usr/lib/node_modules/homebridge-sma-inverter/index.js:148:17)
    at TcpPort.<anonymous> (/usr/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:340:37)
    at TcpPort.emit (events.js:310:20)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/ports/tcpport.js:77:20)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)`

Afterwards Homebridge is rebooting.

**Comment by codyc1515** [comment]
That’s almost certainly the ModBus registers not lining up. Sorry I can’t be of much more help. You may have better luck with Home Assistant with the SMA & HomeKit plugins.

**Comment by solbadguy2010** [comment]
Ok, i'll try that. Thank you
